<?php

namespace AppBundle\Repository;

use UserBundle\Entity\User;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAccountsForUser(User $user)
    {
        $qb = $this->createQueryBuilder('a')
                   ->where('a.user = :user')
                   ->setParameters([
                       'user' => $user,
                   ])
                   ->orderBy('a.date', 'ASC')
                   ->getQuery()
        ;
        return $qb->execute();
    }

    public function getAccountsForAdminGraph(\DateTime $date)
    {
        $qb = $this->createQueryBuilder('a')
                   ->addSelect('u')
                   ->where('u.enabled = 1')
                   ->andWhere('a.date > :date')
                   ->setParameters([
                       'date' => $date,
                   ])
                   ->leftJoin('a.user', 'u')
                   ->orderBy('a.id', 'DESC')
                   ->getQuery()
        ;
        return $qb->execute();
    }

}
