<?php

namespace AppBundle\Repository;

/**
 * ChurchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChurchRepository extends \Doctrine\ORM\EntityRepository
{
}
