<?php

namespace AppBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCities()
    {
        $qb = $this->createQueryBuilder('c')
                   ->addSelect('COUNT(u) as somme')
                   ->leftJoin('c.users', 'u')
                   ->orderBy('somme', 'DESC')
                   ->groupBy('c.name')
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
