<?php

namespace AppBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCities()
    {
        $qb = $this->createQueryBuilder('c')
                   ->addSelect('c')
                   ->orderBy('c.id', 'DESC')
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
