<?php

namespace AppBundle\Repository;
use UserBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserNotificationByStatus($status, User $user)
    {
        $qb = $this->createQueryBuilder('n')
                   ->where('n.user = :user')
                   ->andWhere('n.status = :status')
                   ->setParameters([
                       'user'   => $user,
                       'status' => $status,
                   ])
                   ->orderBy('n.id', 'DESC')
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
