<?php

namespace AppBundle\Repository;

use AppBundle\Utils\User\UserLevel;
use UserBundle\Entity\User;

/**
 * WeaponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @return mixed
     */
    public function getWeaponByLevel(User $user)
    {
        $qb = $this->createQueryBuilder('w')
                   ->where('w.lvl <= :level')
                   ->setParameters([
                       'level' => UserLevel::getLvl($user),
                   ])
                   ->orderBy('w.lvl', 'ASC')
                   ->addOrderBy('w.price', 'DESC')
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
