app:
    prefix: /
    resource: '@AppBundle/Resources/config/routing.yml'

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api
    options:
        expose: true

api_ajax:
    resource: "@ApiBundle/Resources/config/ajax.yml"
    prefix:   /ajax
    options:
        expose: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"