<?php

namespace UserBundle\Repository;

use AppBundle\Entity\City;
use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * Renvoie les 3 meilleurs joueurs
     * @return mixed
     */
    public function getBestUsers()
    {
        $qb = $this->createQueryBuilder('u')
                   ->leftJoin('u.competences', 'c')
                   ->orderBy('c.level', 'DESC')
                   ->addOrderBy('c.life', 'DESC')
                   ->addOrderBy('u.money', 'DESC')
                   ->setMaxResults(3)
                   ->getQuery()
        ;
        return $qb->execute();
    }


    /**
     * @param User $user
     * @return mixed
     */
    public function getUsersByCity(City $city)
    {
        $qb = $this->createQueryBuilder('u')
                   ->where('u.city = :city')
                   ->setParameters([
                       'city' => $city,
                   ])
                   ->getQuery()
        ;
        return $qb->execute();
    }

    public function getUsersWithSavedMoney()
    {
        $qb = $this->createQueryBuilder('u')
                   ->where('u.alive = 1')
                   ->andWhere('u.saving > 0')
                   ->getQuery()
        ;
        return $qb->execute();
    }


    // **  ADMIN  **

    public function getAllUsersForAdmin()
    {
        $qb = $this->createQueryBuilder('u')
                   ->addSelect('c,i')
                   ->leftJoin('u.competences', 'c')
                   ->leftJoin('u.items', 'i')
                   ->orderBy('u.username', 'ASC')
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
