bank_index:
    path: /
    defaults: { _controller: AppBundle:Bank:index}

bank_request:
    path: /loan/request
    defaults: { _controller: AppBundle:Bank:newLoan }

bank_loan_validation:
    path: /loan/validation
    defaults: { _controller: AppBundle:Bank:validation }

bank_loan_refund:
    path: /loan/refund/{id}
    defaults: { _controller: AppBundle:Bank:refund }

bank_loan_cancel:
    path: /loan/cancel/{id}
    defaults: { _controller: AppBundle:Bank:cancel }

bank_saving:
    path: /saving
    defaults: { _controller: AppBundle:Bank:saving }
