# users
user_list:
    path: /list
    defaults: { _controller: AppBundle:Default:users}

# user
user:
    path: /{id}/{username}
    defaults: { _controller: AppBundle:Default:user}

# my profile
myProfile:
    path: /my-profile
    defaults: { _controller: AppBundle:Default:myProfile}

user_levelup:
    path: /level-up
    defaults: { _controller: AppBundle:Default:levelUp}
    methods: [POST]

dead_land:
    path: /dead-land
    defaults: { _controller: AppBundle:Default:deadLand}

rise_again:
    path: /rise_again
    defaults: { _controller: AppBundle:Default:riseAgain }
    methods: [POST]