# users
user_list:
    path: /list
    defaults: { _controller: AppBundle:Default:users}

# user
user:
    path: /{id}/{username}
    defaults: { _controller: AppBundle:Default:user}

# my profile
myProfile:
    path: /my-profile
    defaults: { _controller: AppBundle:Default:myProfile}
