# dojo_index
dojo_index:
    path: /
    defaults: { _controller: AppBundle:Dojo:dojoIndex}

# dojo_add_attack
dojo_add_attack:
    path: /add/attack
    defaults: { _controller: AppBundle:Dojo:dojoAddAttack}

# dojo_add_defense
dojo_add_defense:
    path: /add/defense
    defaults: { _controller: AppBundle:Dojo:dojoAddDefense}

# dojo_add_skill
dojo_add_skill:
    path: /add/skill
    defaults: { _controller: AppBundle:Dojo:dojoAddSkill}
