bank_index_data:
    path:     /bank/my-account-data.json
    defaults: { _controller: ApiBundle:Default:bankData }
    options:
        expose: true
# user_money_data
users_money_data:
    path: /users-money-data
    defaults: { _controller: ApiBundle:Default:userMoneyData}

# purchase_data
purchase_data:
    path: /purchase-data
    defaults: { _controller: ApiBundle:Default:purchaseData}
