bank_index_data:
    path: /bank/my-account-data.json
    defaults: { _controller: ApiBundle:Default:bankData }

# bank users accounts
bank_users_accounts:
    path: /bank/users-accounts.json
    defaults: { _controller: ApiBundle:Default:bankUsersAccounts }

# user_money_data
users_money_data:
    path: /bank/users-money-data.json
    defaults: { _controller: ApiBundle:Default:userMoneyData }

game_oneTenData:
    path: /game/one-ten-data.json
    defaults: { _controller: ApiBundle:Default:game_oneTenData }

game_DicesData:
    path: /game/dices.json
    defaults: { _controller: ApiBundle:Default:gameDicesData }

# purchase_data
purchase_data:
    path: /store/purchase-data.json
    defaults: { _controller: ApiBundle:Default:purchaseData }

# users_level_data
users_level_data:
    path: /users/level-data.json
    defaults: { _controller: ApiBundle:Default:userLevels }

resource_evolution_data:
    path: /resource/evolution.json
    defaults: { _controller: ApiBundle:Default:resourceEvolution }

