<?php

namespace AppBundle\Repository\Stats;

/**
 * CityPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
