<?php

namespace AppBundle\Repository\Stats;

/**
 * ResourceStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
