<?php

namespace AppBundle\Repository\Stats;

/**
 * ResourceStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceStatusRepository extends \Doctrine\ORM\EntityRepository
{

    public function getResourcesEvolution()
    {
        $qb = $this->createQueryBuilder('s')
                   ->addSelect('r')
                   ->leftJoin('s.resource', 'r')
                   ->orderBy('s.date', 'DESC')
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
