# homepage
homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index}

# list actions

listActions:
    path: /actions
    defaults: { _controller: AppBundle:Default:listActions}

# test
test:
    path: /test
    defaults: { _controller: AppBundle:Default:test}

ranking:
    path: /ranking
    defaults: { _controller: AppBundle:Default:ranking}

app_city:
    resource: "@AppBundle/Resources/config/routing/city.yml"
    prefix:   /city

app_bank:
    resource: "@AppBundle/Resources/config/routing/bank.yml"
    prefix:   /bank

app_default_user:
    resource: "@AppBundle/Resources/config/routing/default-user.yml"
    prefix:   /user

app_action:
    resource: "@AppBundle/Resources/config/routing/action.yml"
    prefix:   /action

app_default_store:
    resource: "@AppBundle/Resources/config/routing/store.yml"
    prefix:   /store

app_default_weapon:
    resource: "@AppBundle/Resources/config/routing/weapon.yml"
    prefix:   /weapon

app_game:
    resource: "@AppBundle/Resources/config/routing/game.yml"
    prefix:   /game

app_church:
    resource: "@AppBundle/Resources/config/routing/church.yml"
    prefix:   /church

app_dojo:
    resource: "@AppBundle/Resources/config/routing/dojo.yml"
    prefix:   /dojo

app_trading:
    resource: "@AppBundle/Resources/config/routing/trading.yml"
    prefix:   /trading

app_admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:   /admin