# homepage
homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index}

# list logs

listLogs:
    path: /list/logs
    defaults: { _controller: AppBundle:Default:listLogs}

# test
test:
    path: /test
    defaults: { _controller: AppBundle:Default:test}

ranking:
    path: /ranking
    defaults: { _controller: AppBundle:Default:ranking}

cities:
    path: /cities
    defaults: { _controller: AppBundle:Default:cities}


app_bank:
    resource: "@AppBundle/Resources/config/routing/bank.yml"
    prefix:   /bank

app_default_user:
    resource: "@AppBundle/Resources/config/routing/default-user.yml"
    prefix:   /user

app_action:
    resource: "@AppBundle/Resources/config/routing/action.yml"
    prefix:   /action

app_default_store:
    resource: "@AppBundle/Resources/config/routing/store.yml"
    prefix:   /store

app_default_weapon:
    resource: "@AppBundle/Resources/config/routing/weapon.yml"
    prefix:   /weapon

app_game:
    resource: "@AppBundle/Resources/config/routing/game.yml"
    prefix:   /game

app_admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:   /admin