<?php

namespace AppBundle\Repository\Action;

use UserBundle\Entity\User;

/**
 * AliveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliveRepository extends \Doctrine\ORM\EntityRepository implements ActionRepositoryInterface
{
    public function getByUser(User $user, \DateTime $date)
    {
        $qb = $this->createQueryBuilder('a')
                   ->where('a.user = :user')
                   ->andWhere('a.date >= :date')
                   ->setParameters([
                       'user' => $user,
                       'date' => $date,
                   ])
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
