<?php

namespace AppBundle\Repository\Action;

use UserBundle\Entity\User;

/**
 * AttackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttackRepository extends \Doctrine\ORM\EntityRepository implements ActionRepositoryInterface
{
    public function getByUser(User $user, \DateTime $date)
    {
        $qb = $this->createQueryBuilder('a')
                   ->addSelect('w,att,v')
                   ->leftJoin('a.weapons', 'w')
                   ->leftJoin('a.attacker', 'att')
                   ->leftJoin('a.victim', 'v')
                   ->where('a.attacker = :user OR a.victim = :user')
                   ->andWhere('a.date >= :date')
                   ->setParameters([
                       'user' => $user,
                       'date' => $date,
                   ])
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
