<?php

namespace AppBundle\Repository\Action;

/**
 * CityMoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityMoveRepository extends \Doctrine\ORM\EntityRepository
{
}
