<?php

namespace AppBundle\Repository\Action;

use UserBundle\Entity\User;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository implements ActionRepositoryInterface
{

    public function getGameInfos($game)
    {
        $qb = $this->createQueryBuilder('g')
                   ->select('SUM(g.status) as total_win,COUNT(g.id) as total')
                   ->where('g.game = :game')
                   ->setParameters([
                       'game' => $game,
                   ])
                   ->getQuery()
        ;
        return $qb->execute();
    }

    public function getByUser(User $user, \DateTime $date)
    {
        $qb = $this->createQueryBuilder('g')
                   ->where('g.user = :user')
                   ->andWhere('g.date > :date')
                   ->setParameters([
                       'user' => $user,
                       'date' => $date,
                   ])
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
