<?php

namespace AppBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * SavingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavingRepository extends EntityRepository implements ActionRepositoryInterface
{
    public function getByUser(User $user, \DateTime $date)
    {
        $qb = $this->createQueryBuilder('s')
                   ->addSelect('u')
                   ->leftJoin('s.user', 'u')
                   ->where('s.user = :user')
                   ->andWhere('s.date > :date')
                   ->setParameters([
                       'user' => $user,
                       'date' => $date,
                   ])
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
