<?php

namespace AppBundle\Repository\Action;

use UserBundle\Entity\User;

/**
 * StealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StealRepository extends \Doctrine\ORM\EntityRepository implements ActionRepositoryInterface
{
    public function getByUser(User $user, \DateTime $date)
    {
        $qb = $this->createQueryBuilder('s')
                   ->where('s.burglar = :user OR s.victim = :user')
                   ->andWhere('s.date > :date')
                   ->setParameters([
                       'user' => $user,
                       'date' => $date,
                   ])
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
