<?php

namespace AppBundle\Repository\Bank;

use AppBundle\Entity\Bank\Loan;
use UserBundle\Entity\User;

/**
 * LoanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLoansForUser(User $user)
    {
        $qb = $this->createQueryBuilder('l')
                   ->addSelect('u')
                   ->leftJoin('l.user', 'u')
                   ->where('l.user = :user')
                   ->andWhere('l.status != :closed')
                   ->andWhere('l.status != :refused')
                   ->andWhere('l.status != :canceled')
                   ->setParameters(
                       [
                           'closed'   => Loan::STATUS_CLOSED,
                           'refused'  => Loan::STATUS_REFUSED,
                           'canceled' => Loan::STATUS_CANCELED,
                           'user'     => $user,
                       ]
                   )
                   ->getQuery()
        ;
        return $qb->execute();
    }

    public function findAllLoansByUser(User $user)
    {
        $qb = $this->createQueryBuilder('l')
                   ->where('l.user = :user')
                   ->setParameter('user', $user)
                   ->orderBy('l.date', 'DESC')
                   ->getQuery()
        ;
        return $qb->execute();
    }
}
