<?php

namespace AppBundle\Repository\Bank;

/**
 * RefundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefundRepository extends \Doctrine\ORM\EntityRepository
{
}
